---
- hosts: db_server
  vars:
    created_username: ubuntu
  tasks:
    # - name: Allow user to run sudo commands without password
    #   community.general.sudoers:
    #     name: "{{ created_username }}"-sudo-allow
    #     state: present
    #     user: "{{ created_username }}"
    #     commands: ALL
    #     nopassword: true
    #   become: true

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
      become: true

    - name: Allow all access to SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp
      become: true

    - name: UFW - Enable and deny by default
      ufw:
        state: enabled
        default: deny
      become: true

    - name: Update apt and install Postgres
      apt:
        pkg:
          - postgres
        state: latest
        update_cache: true
      become: true

  #     become: true

  #   - name: UFW - Enable and deny by default
  #     ufw:
  #       state: enabled
  #       default: deny
  #     become: true

  #   - name: Update apt and install HAProxy
  #     apt:
  #       pkg:
  #         - haproxy
  #       state: latest
  #       update_cache: true
  #     become: true

  #   - name: copy the haproxy config to the lb
  #     template:
  #       src: ~/ansible/templates/haproxy.cfg
  #       dest: /etc/haproxy/haproxy.cfg
  #       owner: root
  #       group: root
  #     notify:
  #     - Restart HAProxy
  #     become: true

  # handlers:
  #   - name: Restart HAProxy
  #     service:
  #       name: haproxy
  #       state: restarted
  #     become: true



    # - name: Creates ansible directory
    #   file:
    #     path: /home/ubuntu/ansible/playbooks
    #     state: directory
    #     owner: "{{ created_username }}"
    #     group: "{{ created_username }}"

    # - name: copy the lb ssh key to control node
    #   copy:
    #     src: keys/lb-ssh-key.pem
    #     dest: /home/ubuntu/ansible/lb-ssh-key.pem
    #     owner: "{{ created_username }}"
    #     group: "{{ created_username }}"

    # - name: copy the db ssh key to control node
    #   copy:
    #     src: keys/db-ssh-key.pem
    #     dest: /home/ubuntu/ansible/db-ssh-key.pem
    #     owner: "{{ created_username }}"
    #     group: "{{ created_username }}"