---
- hosts: lb_server
  vars:
    created_username: ubuntu
  tasks:
    - name: Allow user to run sudo commands without password
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: true

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
      become: true
      become_method: sudo

    - name: Allow all access to SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp
      become: true
      become_method: sudo

    - name: Allow all access to HTTP
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      become: true
      become_method: sudo

    - name: Allow all access to HTTPS
      ufw:
        rule: allow
        port: '443'
        proto: tcp
      become: true
      become_method: sudo

    - name: UFW - Enable and deny by default
      ufw:
        state: enabled
        default: deny
      become: true
      become_method: sudo

    - name: Update apt and install Nginx
      apt:
        pkg:
          - nginx
        state: latest
        update_cache: true
      become: true
      become_method: sudo

    - name: copy the nginx config
      copy:
        src: /home/ubuntu/ansible/templates/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
      become: true
      become_method: sudo

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: true
      become_method: sudo