name: devops-challenge

# env:
#   DEPLOY_DIR: /infrastructure
#   BACKEND_CONF: ../environment/backend.conf

on:
  push:
    branches:
      - main

jobs:
  devops-challenge:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Debug
        id: debug
        shell: bash
        # working-directory: $DEPLOY_DIR
        run: |
          ls -la && pwd
        
      - name: Terraform Init
        id: init
        shell: bash
        working-directory: infrastructure
        run: |
          terraform init -input=false -backend-config=../environment/backend.conf
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Terraform Validate
        id: validate
        shell: bash
        working-directory: infrastructure
        run: |
          terraform validate

      - name: Terraform Plan
        id: plan
        shell: bash
        working-directory: infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_ansible_private_key: ${{ secrets.ANSIBLE_SSH_KEY }}
        run: |
          terraform plan -out tfplan -input=false -lock=false 
          terraform show -json tfplan > plan.json
